name: CI/CD for Quarkus Application

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  Release:
    runs-on: ubuntu-latest
    environment: DEVSECOPS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Packages to GitHub
        uses: ./.github/actions/package
        with: 
          java-version: '17'
          SETTING_KEY: ${{ secrets.SETTING_KEY }}
          USER: ${{ secrets.USER }}
